source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Anthology_Tests' do
  platform :osx, 10.11
  pod 'Anthology', :path => ".."

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
