# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm info
- gem env
- echo $GEM_HOME
- echo $PATH
- rvm --default use 2.2
- rvm 2.2
- rvm info
- gem env
- echo $GEM_HOME
- echo $PATH
- gem list cocoapods
- gem uninstall cocoapods 0.39.0
- gem list cocoapods
- gem install cocoapods --prerelease --verbose
- gem list cocoapods
- which pod
- pod --version
- /Users/travis/.rvm/gems/ruby-2.2.1/bin/pod --version
- gem install xcpretty
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild build -workspace Example/Anthology.xcworkspace -scheme Anthology -sdk macosx10.11 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
