# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- brew update
- brew outdated ruby || brew upgrade ruby
- ruby --version
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Anthology.xcworkspace -scheme Anthology -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
