# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
notifications:
  email: false
before_install:
- rvm --default use 2.2
install:
- bundle install
script:
- set -o pipefail && xcodebuild build -workspace Anthology.xcworkspace -scheme Anthology ONLY_ACTIVE_ARCH=NO | xcpretty
- bundle exec pod lib lint
