# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm --default use 2.2
- rvm use 2.2
- gem install cocoapods --pre
- gem install xcpretty
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild build -workspace Example/Anthology.xcworkspace -scheme Anthology -sdk macosx10.11 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
